[package]
name = "near-da-http-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
axum = "0.6"
clap = { version = "4.4", features = ["derive"] }
near-da-rpc = { path = "../../crates/da-rpc" }
near-da-primitives = { path = "../../crates/primitives" }
http-api-data = { path = "../../crates/http-api-data" }
serde = "1"
serde_json = "1.0.108"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.75"
