[package]
name = "near-da-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde_with = { version = "*", default-features = false, features = [
  "hex",
  "base64",
  "macros",
] }
serde = { version = "*", default-features = false, features = ["derive"] }
borsh = { version = "1", default-features = false, features = ["derive"] }

near-primitives = { version = "*", optional = true }

[dev-dependencies]
hex = "*"

[features]
default = ["std", "crypto"]
std = ["serde_with/std", "serde/std", "borsh/std"]
crypto = ["near-primitives"]
